config/routes.rb
Rails.application.routes.draw do

  root "pages#home"
  get '/about', to: 'pages#about'
  get '/help', to: 'pages#help'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    resources :todos
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :description, presence: true
end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

class User < ApplicationRecord
  has_many :todos, dependent: :destroy
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true, uniqueness: true, on: :create, email: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/other_controller.rb
class OtherController < ApplicationController
  def mytest

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def help  
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:edit, :update, :show, :destroy]
  def new
    @user = User.find(params[:user_id])
    @todo = Todo.new
    @action = "Create"
  end

  def create
    @user = User.find(params[:user_id])
    @todo = @user.todos.create(todo_params)
    if @todo.save
      flash[:notice] = ["Success!","The new todo has successfully been saved"]
      redirect_to user_todo_path(@user,@todo)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
    @action = "Edit"
  end

  def update
    if @todo.update(todo_params)
      flash[:notice] = ["Success!","Your todo has been updated"]
      redirect_to user_todo_path(@user,@todo)
    else
      render 'edit'
    end
  end

  def index
    @user = User.find(params[:user_id])
    @todos = @user.todos.all
  end

  def destroy
    if @todo.destroy
      flash[:notice] = ["Success!","The selected todo has been deleted"]
      redirect_to user_todos_path(@user)
    else
      render 'destroy'
    end
  end

  private

  def set_todo
    @user = User.find(params[:user_id])
    @todo = @user.todos.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:name, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = ["Success!","You have successfully signed up!"]
      redirect_to user_todos_path @user
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:firstname, :lastname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% if flash[:notice] %>
<div class="alert alert-success" role="alert">
  <b>
    <%= flash[:notice][0] %>
  </b>
  <%= flash[:notice][1] %>
</div>
<% end %>
<% if flash[:alert] %>
<div class="alert alert-warning" role="alert">
  <b>
    <%= flash[:alert][0] %>
  </b>
  <%= flash[:alert][1] %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mich Todo App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" %>
    <!-- jQuery library -->
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" %>
    <!-- Latest compiled JavaScript -->
    <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/other/mytest.html.erb
<h2>I'm an adventurous test!</h2>

app/views/pages/about.html.erb
<h1>I'm the About page!</h1>
<a href="/">Go back to home</a>

app/views/pages/help.html.erb
<h1>I'm the help page!</h1>
<p>
  I'm here to help you should you have any issues
</p>
<a href="/">Return to main page</a>

app/views/pages/home.html.erb
<h1>Hello world!</h1>
<hr />
<a href="/about">go to about page</a>
<hr />
<a href="/help">go to help page</a>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
<h2>The following errors prevented your todo from being saved</h2>
<ul>
  <% @todo.errors.full_messages.each do |msg|%>
  <li>
    <%= msg %>
  </li>
  <% end %>
</ul>
<% end %>

<%= form_for [@user,@todo] do |f|  %>
<div class="form-group">
  <%= f.label :name, "Title"  %>
  <%= f.text_field :name, class:"form-control" %>
</div>
<div class="form-group">
  <%= f.label :description, "Description" %>
  <%= f.text_area :description, size: "60x12", class:"form-control" %>
</div>
<%= f.submit "#{@action} Todo", class: "btn btn-default" %>
<%= link_to "Cancel", user_todos_path(@user), class: "btn btn-warning" %>
<% end %>

app/views/todos/destroy.html.erb
<% if @todo.errors.any? %>
  <h2>The following errors prevented your todo from being deleted</h2>
  <ul>
    <% @todo.errors.full_messages.each do |msg|%>
      <li>
        <%= msg %>
      </li>
    <% end %>
  </ul>
<% end %>
<%= link_to "Go to index", todos_path, class: "btn btn-warning" %>

app/views/todos/edit.html.erb
<h1>Edit an existing Todo</h1>
<%= render 'form' %>

app/views/todos/index.html.erb
<h2>List of all your todos</h2>
<% @todos.each do |todo| %>
  <div class="row">
    <div class="col-xs-3">
      Title: <b><%= todo.name %></b>
    </div>
    <div class="col-xs-9">
      Description:
      <p>
        <%= todo.description %>
      </p>
      <%= link_to "Details", user_todo_path(@user,todo), class: "btn btn-primary" %>
      <%= link_to "Edit", edit_user_todo_path(@user,todo), class: "btn btn-info" %>
      <%= link_to "Delete", user_todo_path(@user,todo), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
    </div>
  </div>
  <hr />
<% end %>
<%= link_to "Create new todo", new_user_todo_path(@user), class: "btn btn-success" %>

app/views/todos/new.html.erb
<h1>Create a new Todo</h1>
<%= render 'form' %>

app/views/todos/show.html.erb
<div class="row">
  <div class="col-xs-8">

  <h3>
    Title: <%= @todo.name %>
  </h3>
  <p>
    Description: <%= @todo.description %>
  </p>
  <%= link_to "Go to index", user_todos_path(@user), class: "btn btn-warning" %>
  </div>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<h2>The following errors prevented you from signing up</h2>
<ul>
  <% @user.errors.full_messages.each do |msg|%>
  <li>
    <%= msg %>
  </li>
  <% end %>
</ul>
<% end %>

<%= form_for @user do |f|  %>
<div class="form-group">
  <%= f.label :firstname, "First name"  %>
  <%= f.text_field :firstname, class:"form-control" %>
  <%= f.label :lastname, "Last name"  %>
  <%= f.text_field :lastname, class:"form-control" %>
</div>
<div class="form-group">
  <%= f.label :email, "Your Email"  %>
  <%= f.email_field :email, class:"form-control" %>
</div>
<%= f.submit "Sign up!", class: "btn btn-default" %>
<%= link_to "Cancel", root_path, class: "btn btn-warning" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up!</h1>
<%= render 'form' %>